"""empty message

Revision ID: dca49fe854c9
Revises: 9f78bff20e0f
Create Date: 2021-08-09 06:07:16.215670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca49fe854c9'
down_revision = '9f78bff20e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('product', sa.Integer(), nullable=True))
    op.drop_index('ix_cart_user_id', table_name='cart')
    op.create_index(op.f('ix_cart_user'), 'cart', ['user'], unique=False)
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_product_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'user', ['user'], ['id'])
    op.create_foreign_key(None, 'cart', 'product', ['product'], ['id'])
    op.drop_column('cart', 'product_id')
    op.drop_column('cart', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_product_id_fkey', 'cart', 'product', ['product_id'], ['id'])
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_cart_user'), table_name='cart')
    op.create_index('ix_cart_user_id', 'cart', ['user_id'], unique=False)
    op.drop_column('cart', 'product')
    op.drop_column('cart', 'user')
    # ### end Alembic commands ###
