"""empty message

Revision ID: e4bee4865189
Revises: dca49fe854c9
Create Date: 2021-08-09 06:14:41.985522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4bee4865189'
down_revision = 'dca49fe854c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_index('ix_cart_user', table_name='cart')
    op.create_index(op.f('ix_cart_user_id'), 'cart', ['user_id'], unique=False)
    op.drop_constraint('cart_user_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_product_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'])
    op.drop_column('cart', 'product')
    op.drop_column('cart', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('product', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_product_fkey', 'cart', 'product', ['product'], ['id'])
    op.create_foreign_key('cart_user_fkey', 'cart', 'user', ['user'], ['id'])
    op.drop_index(op.f('ix_cart_user_id'), table_name='cart')
    op.create_index('ix_cart_user', 'cart', ['user'], unique=False)
    op.drop_column('cart', 'product_id')
    op.drop_column('cart', 'user_id')
    # ### end Alembic commands ###
